Many modules are hidden in this stack. Use "module --show_hidden spider SOFTWARE" if you are not able to find the required software
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x145de2d4ead0>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x145de2d597d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x145de2d59f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x145de2d5af90>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x145de2d5bb50>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/pip/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x152749bdd210>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/ngsolve/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x152749c05150>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/ngsolve/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x152749c05c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/ngsolve/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x152749c06510>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/ngsolve/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x152749c071d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/ngsolve/
Traceback (most recent call last):
  File "/cluster/home/rschoenholze/Bsc_Thesis/unstructured/d3l2_unstr.py", line 145, in <module>
    plt.savefig("/cluster/home/rschoenholze/Bsc_Thesis/unstructured/d3l2_minEV_unstr.pdf" %j)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
TypeError: not all arguments converted during string formatting
